### ISSUE TITLE
MAIN: 27ms regression on S7 7/3, 13ms until 7/13; big VIEW regression too; perf commit shows downward trend

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#131] opened 2020-07-15 21:47 UTC

**Comment by mcomella** [comment] 2020-07-22 22:59
Repurposing this issue to focus on the regression.

Triage: we don't have good tools to identify the cause so moving to low impact backlog.

**Comment by mcomella** [comment] 2020-08-03 19:06
Closing: we generally haven't found startup regression investigations fruitful so the tickets are low priority. They're are a lot of them and they're hard to manipulate/track in GH so we're tracking on this spreadsheet instead: https://docs.google.com/spreadsheets/d/1hiKe-1KCs8mbyFu9Fik5SIIe5I-XjEilnaIqkfcnvYo/edit#gid=0

**Closed as completed by mcomella** 2020-08-03 19:06 UTC
